const WEAKNESSES = [
	{
		id: 1,
		name: 'Marketing',
		statsBuffer: {
			marketing: -50,
			productivity: -10,
			creativity: 0,
			financeManagement: -5,
			humanResources: -15,
			leadership: -15,
			communication: -5,
			technicalSkill: 0,
			negotiation: -5,
			strategy: -10,
			adaptability: -5,
			stressManagement: -5,
			riskManagement: 0,
			analyticalThinking: 0,
			resilience: 0,
			innovation: -5,
			reputation: 0,
			learningSpeed: 0,
			luck: -10,
			ambition: -5,
		},
	},
	{
		id: 2,
		name: 'Productivity',
		statsBuffer: {
			marketing: -10,
			productivity: -50,
			creativity: 0,
			financeManagement: -10,
			humanResources: 0,
			leadership: -15,
			communication: 0,
			technicalSkill: 0,
			negotiation: 0,
			strategy: -10,
			adaptability: -5,
			stressManagement: -5,
			riskManagement: 0,
			analyticalThinking: 0,
			resilience: -5,
			innovation: 0,
			reputation: -5,
			learningSpeed: -15,
			luck: -5,
			ambition: -15,
		},
	},
	{
		id: 3,
		name: 'Creativity',
		statsBuffer: {
			marketing: -10,
			productivity: 0,
			creativity: -50,
			financeManagement: 0,
			humanResources: -10,
			leadership: 0,
			communication: -5,
			technicalSkill: -5,
			negotiation: 0,
			strategy: 0,
			adaptability: -10,
			stressManagement: -10,
			riskManagement: 0,
			analyticalThinking: 0,
			resilience: 0,
			innovation: -15,
			reputation: 0,
			learningSpeed: -10,
			luck: -10,
			ambition: -10,
		},
	},
	{
		id: 4,
		name: 'Finance Management',
		statsBuffer: {
			marketing: -5,
			productivity: -10,
			creativity: 0,
			financeManagement: -50,
			humanResources: -5,
			leadership: -5,
			communication: -10,
			technicalSkill: -5,
			negotiation: -5,
			strategy: -10,
			adaptability: -5,
			stressManagement: -5,
			riskManagement: -15,
			analyticalThinking: -15,
			resilience: 0,
			innovation: 0,
			reputation: -5,
			learningSpeed: 0,
			luck: 0,
			ambition: 0,
		},
	},
	{
		id: 5,
		name: 'Human Resources',
		statsBuffer: {
			marketing: 0,
			productivity: 0,
			creativity: 0,
			financeManagement: -5,
			humanResources: -50,
			leadership: -15,
			communication: -15,
			technicalSkill: 0,
			negotiation: -15,
			strategy: -10,
			adaptability: -5,
			stressManagement: -15,
			riskManagement: -5,
			analyticalThinking: 0,
			resilience: 0,
			innovation: 0,
			reputation: -5,
			learningSpeed: 0,
			luck: -5,
			ambition: -5,
		},
	},
	{
		id: 6,
		name: 'Leadership',
		statsBuffer: {
			marketing: -5,
			productivity: -5,
			creativity: 0,
			financeManagement: -5,
			humanResources: -10,
			leadership: -50,
			communication: -10,
			technicalSkill: 0,
			negotiation: 0,
			strategy: -10,
			adaptability: -5,
			stressManagement: -5,
			riskManagement: -5,
			analyticalThinking: -5,
			resilience: -10,
			innovation: -5,
			reputation: -5,
			learningSpeed: -5,
			luck: -5,
			ambition: -5,
		},
	},
	{
		id: 7,
		name: 'Communication',
		statsBuffer: {
			marketing: -5,
			productivity: -5,
			creativity: -5,
			financeManagement: 0,
			humanResources: -5,
			leadership: -5,
			communication: -50,
			technicalSkill: -5,
			negotiation: -10,
			strategy: -5,
			adaptability: -5,
			stressManagement: -5,
			riskManagement: -5,
			analyticalThinking: -5,
			resilience: -5,
			innovation: -5,
			reputation: -5,
			learningSpeed: -5,
			luck: -5,
			ambition: -5,
		},
	},
	{
		id: 8,
		name: 'Technical Skill',
		statsBuffer: {
			marketing: 0,
			productivity: -5,
			creativity: 0,
			financeManagement: -5,
			humanResources: -5,
			leadership: -5,
			communication: 0,
			technicalSkill: -50,
			negotiation: 0,
			strategy: -5,
			adaptability: -10,
			stressManagement: -5,
			riskManagement: -5,
			analyticalThinking: -10,
			resilience: -10,
			innovation: -10,
			reputation: 0,
			learningSpeed: -10,
			luck: -5,
			ambition: -5,
		},
	},
	{
		id: 9,
		name: 'Negotiation',
		statsBuffer: {
			marketing: -5,
			productivity: -5,
			creativity: 0,
			financeManagement: -5,
			humanResources: -5,
			leadership: -5,
			communication: -10,
			technicalSkill: 0,
			negotiation: -50,
			strategy: -10,
			adaptability: -5,
			stressManagement: -5,
			riskManagement: -5,
			analyticalThinking: -5,
			resilience: -5,
			innovation: -5,
			reputation: -5,
			learningSpeed: -5,
			luck: -5,
			ambition: -5,
		},
	},
	{
		id: 10,
		name: 'Strategy',
		statsBuffer: {
			marketing: -5,
			productivity: -5,
			creativity: 0,
			financeManagement: -5,
			humanResources: -5,
			leadership: -5,
			communication: -5,
			technicalSkill: 0,
			negotiation: -5,
			strategy: -50,
			adaptability: -5,
			stressManagement: -5,
			riskManagement: -10,
			analyticalThinking: -10,
			resilience: -5,
			innovation: -5,
			reputation: 0,
			learningSpeed: -5,
			luck: -5,
			ambition: -5,
		},
	},
	{
		id: 11,
		name: 'Adaptability',
		statsBuffer: {
			marketing: 0,
			productivity: -5,
			creativity: -5,
			financeManagement: 0,
			humanResources: -5,
			leadership: -5,
			communication: -5,
			technicalSkill: 0,
			negotiation: 0,
			strategy: -5,
			adaptability: -50,
			stressManagement: -10,
			riskManagement: -5,
			analyticalThinking: -5,
			resilience: -10,
			innovation: -5,
			reputation: 0,
			learningSpeed: -5,
			luck: -5,
			ambition: -5,
		},
	},
	{
		id: 12,
		name: 'Stress Management',
		statsBuffer: {
			marketing: -5,
			productivity: -5,
			creativity: 0,
			financeManagement: -5,
			humanResources: -5,
			leadership: -5,
			communication: -5,
			technicalSkill: 0,
			negotiation: -5,
			strategy: -5,
			adaptability: -10,
			stressManagement: -50,
			riskManagement: -5,
			analyticalThinking: -5,
			resilience: -10,
			innovation: -5,
			reputation: 0,
			learningSpeed: -5,
			luck: -5,
			ambition: -5,
		},
	},
	{
		id: 13,
		name: 'Risk Management',
		statsBuffer: {
			marketing: -5,
			productivity: -5,
			creativity: 0,
			financeManagement: -10,
			humanResources: -5,
			leadership: -5,
			communication: -5,
			technicalSkill: 0,
			negotiation: -5,
			strategy: -10,
			adaptability: -5,
			stressManagement: -5,
			riskManagement: -50,
			analyticalThinking: -10,
			resilience: -5,
			innovation: -5,
			reputation: 0,
			learningSpeed: -5,
			luck: -5,
			ambition: -5,
		},
	},
	{
		id: 14,
		name: 'Analytical Thinking',
		statsBuffer: {
			marketing: -5,
			productivity: -5,
			creativity: 0,
			financeManagement: -5,
			humanResources: 0,
			leadership: -5,
			communication: -5,
			technicalSkill: -5,
			negotiation: 0,
			strategy: -10,
			adaptability: -5,
			stressManagement: -5,
			riskManagement: -10,
			analyticalThinking: -50,
			resilience: -5,
			innovation: -5,
			reputation: 0,
			learningSpeed: -5,
			luck: -5,
			ambition: -5,
		},
	},
	{
		id: 15,
		name: 'Resilience',
		statsBuffer: {
			marketing: 0,
			productivity: -5,
			creativity: 0,
			financeManagement: -5,
			humanResources: -5,
			leadership: -5,
			communication: -5,
			technicalSkill: 0,
			negotiation: -5,
			strategy: -5,
			adaptability: -10,
			stressManagement: -10,
			riskManagement: -5,
			analyticalThinking: -5,
			resilience: -50,
			innovation: 0,
			reputation: 0,
			learningSpeed: -5,
			luck: -5,
			ambition: -5,
		},
	},
	{
		id: 16,
		name: 'Innovation',
		statsBuffer: {
			marketing: -5,
			productivity: -5,
			creativity: -15,
			financeManagement: 0,
			humanResources: -5,
			leadership: -5,
			communication: -5,
			technicalSkill: -10,
			negotiation: 0,
			strategy: -5,
			adaptability: -5,
			stressManagement: -5,
			riskManagement: -5,
			analyticalThinking: -5,
			resilience: 0,
			innovation: -50,
			reputation: -5,
			learningSpeed: -5,
			luck: -5,
			ambition: -5,
		},
	},
	{
		id: 17,
		name: 'Reputation',
		statsBuffer: {
			marketing: -10,
			productivity: 0,
			creativity: 0,
			financeManagement: 0,
			humanResources: -5,
			leadership: -5,
			communication: -10,
			technicalSkill: 0,
			negotiation: -10,
			strategy: -5,
			adaptability: -5,
			stressManagement: -5,
			riskManagement: -5,
			analyticalThinking: -5,
			resilience: -5,
			innovation: -5,
			reputation: -50,
			learningSpeed: 0,
			luck: -5,
			ambition: -5,
		},
	},
	{
		id: 18,
		name: 'Learning Speed',
		statsBuffer: {
			marketing: 0,
			productivity: -5,
			creativity: -5,
			financeManagement: 0,
			humanResources: -5,
			leadership: -5,
			communication: -5,
			technicalSkill: -5,
			negotiation: 0,
			strategy: -5,
			adaptability: -10,
			stressManagement: -5,
			riskManagement: -5,
			analyticalThinking: -10,
			resilience: -5,
			innovation: -5,
			reputation: 0,
			learningSpeed: -50,
			luck: -5,
			ambition: -5,
		},
	},
	{
		id: 19,
		name: 'Luck',
		statsBuffer: {
			marketing: -5,
			productivity: -5,
			creativity: -5,
			financeManagement: 0,
			humanResources: -5,
			leadership: -5,
			communication: -5,
			technicalSkill: 0,
			negotiation: -5,
			strategy: -5,
			adaptability: -10,
			stressManagement: -10,
			riskManagement: -5,
			analyticalThinking: -5,
			resilience: -10,
			innovation: -5,
			reputation: -5,
			learningSpeed: -5,
			luck: -50,
			ambition: -5,
		},
	},
	{
		id: 20,
		name: 'Ambition',
		statsBuffer: {
			marketing: 0,
			productivity: -10,
			creativity: 0,
			financeManagement: 0,
			humanResources: 0,
			leadership: -10,
			communication: -5,
			technicalSkill: 0,
			negotiation: 0,
			strategy: -10,
			adaptability: -5,
			stressManagement: -5,
			riskManagement: -5,
			analyticalThinking: -5,
			resilience: -5,
			innovation: -5,
			reputation: -5,
			learningSpeed: -5,
			luck: -5,
			ambition: -50,
		},
	},
];

export default WEAKNESSES;
