export type PlayerStatsType = {
	marketing: number;
	productivity: number;
	creativity: number;
	financeManagement: number;
	humanResources: number;
	leadership: number;
	communication: number;
	technicalSkill: number;
	negotiation: number;
	strategy: number;
	adaptability: number;
	stressManagement: number;
	riskManagement: number;
	analyticalThinking: number;
	resilience: number;
	innovation: number;
	reputation: number;
	learningSpeed: number;
	luck: number;
	ambition: number;
};
