import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import { GameProvider } from '@/context/gameContext';

const montserrat = Montserrat({
	variable: '--font-montserrat',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Platora',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			{/* GameModeProvider */}
			<GameProvider>
				<body className={`${montserrat.variable} antialiased`}>{children}</body>
			</GameProvider>
		</html>
	);
}
